"""create catalog tables

Revision ID: f43171814116
Revises: 
Create Date: 2025-12-26 09:56:10.573544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43171814116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_category'), 'catalog_items', ['category'], unique=False)
    op.create_index(op.f('ix_catalog_items_id'), 'catalog_items', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_items_item_code'), 'catalog_items', ['item_code'], unique=True)
    op.create_index(op.f('ix_catalog_items_make'), 'catalog_items', ['make'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_effective_from'), 'price_lists', ['effective_from'], unique=False)
    op.create_index(op.f('ix_price_lists_effective_to'), 'price_lists', ['effective_to'], unique=False)
    op.create_index(op.f('ix_price_lists_id'), 'price_lists', ['id'], unique=False)
    op.create_table('catalog_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('sku_type', sa.Enum('PRIMARY', 'BUILT_IN', 'ADDON', 'OPTIONAL', 'MANDATORY_SPLIT', name='skutype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('series', sa.String(length=200), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_currency', sa.String(length=3), nullable=False),
    sa.Column('current_price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make', 'sku_code', name='uq_catalog_sku_make_code')
    )
    op.create_index('idx_catalog_sku_make_code', 'catalog_skus', ['make', 'sku_code'], unique=False)
    op.create_index(op.f('ix_catalog_skus_catalog_item_id'), 'catalog_skus', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_catalog_skus_id'), 'catalog_skus', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_skus_make'), 'catalog_skus', ['make'], unique=False)
    op.create_index(op.f('ix_catalog_skus_series'), 'catalog_skus', ['series'], unique=False)
    op.create_index(op.f('ix_catalog_skus_sku_code'), 'catalog_skus', ['sku_code'], unique=False)
    op.create_table('sku_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['catalog_skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'price_list_id', name='uq_sku_price_list')
    )
    op.create_index('idx_sku_price_effective', 'sku_prices', ['sku_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index(op.f('ix_sku_prices_effective_from'), 'sku_prices', ['effective_from'], unique=False)
    op.create_index(op.f('ix_sku_prices_effective_to'), 'sku_prices', ['effective_to'], unique=False)
    op.create_index(op.f('ix_sku_prices_id'), 'sku_prices', ['id'], unique=False)
    op.create_index(op.f('ix_sku_prices_import_batch_id'), 'sku_prices', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_sku_prices_price_list_id'), 'sku_prices', ['price_list_id'], unique=False)
    op.create_index(op.f('ix_sku_prices_sku_id'), 'sku_prices', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sku_prices_sku_id'), table_name='sku_prices')
    op.drop_index(op.f('ix_sku_prices_price_list_id'), table_name='sku_prices')
    op.drop_index(op.f('ix_sku_prices_import_batch_id'), table_name='sku_prices')
    op.drop_index(op.f('ix_sku_prices_id'), table_name='sku_prices')
    op.drop_index(op.f('ix_sku_prices_effective_to'), table_name='sku_prices')
    op.drop_index(op.f('ix_sku_prices_effective_from'), table_name='sku_prices')
    op.drop_index('idx_sku_price_effective', table_name='sku_prices')
    op.drop_table('sku_prices')
    op.drop_index(op.f('ix_catalog_skus_sku_code'), table_name='catalog_skus')
    op.drop_index(op.f('ix_catalog_skus_series'), table_name='catalog_skus')
    op.drop_index(op.f('ix_catalog_skus_make'), table_name='catalog_skus')
    op.drop_index(op.f('ix_catalog_skus_id'), table_name='catalog_skus')
    op.drop_index(op.f('ix_catalog_skus_catalog_item_id'), table_name='catalog_skus')
    op.drop_index('idx_catalog_sku_make_code', table_name='catalog_skus')
    op.drop_table('catalog_skus')
    op.drop_index(op.f('ix_price_lists_id'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_effective_to'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_effective_from'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_catalog_items_make'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_item_code'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_category'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###

