"""
Error Code Constants

Centralized error codes for consistency across all API endpoints.
Matches Error Taxonomy: docs/PHASE_5/01_CATEGORY_B_API/03_ERROR_TAXONOMY.md
"""


class ErrorCodes:
    # Validation (400)
    VALIDATION_ERROR = "VALIDATION_ERROR"
    VALIDATION_MISSING_REQUIRED = "VALIDATION_MISSING_REQUIRED"
    VALIDATION_INVALID_PRICE = "VALIDATION_INVALID_PRICE"
    VALIDATION_INVALID_CURRENCY = "VALIDATION_INVALID_CURRENCY"
    VALIDATION_INVALID_SKU = "VALIDATION_INVALID_SKU"
    VALIDATION_INVALID_STAGE = "VALIDATION_INVALID_STAGE"
    VALIDATION_INVALID_PAGINATION = "VALIDATION_INVALID_PAGINATION"
    VALIDATION_MISSING_TENANT = "VALIDATION_MISSING_TENANT"

    # Auth (401)
    AUTH_MISSING_TOKEN = "AUTH_MISSING_TOKEN"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"

    # Permission (403)
    PERMISSION_DENIED = "PERMISSION_DENIED"
    PERMISSION_INSUFFICIENT_ROLE = "PERMISSION_INSUFFICIENT_ROLE"
    PERMISSION_BULK_DISALLOWED = "PERMISSION_BULK_DISALLOWED"

    # Not Found (404)
    NOT_FOUND_RESOURCE = "NOT_FOUND_RESOURCE"
    NOT_FOUND_ITEM = "NOT_FOUND_ITEM"
    NOT_FOUND_SKU = "NOT_FOUND_SKU"
    NOT_FOUND_QUOTATION = "NOT_FOUND_QUOTATION"
    NOT_FOUND_LINE_ITEM = "NOT_FOUND_LINE_ITEM"

    # Conflict (409)
    CONFLICT_BUSINESS_RULE = "CONFLICT_BUSINESS_RULE"
    CONFLICT_LINE_ITEM_LOCKED = "CONFLICT_LINE_ITEM_LOCKED"
    CONFLICT_IMPORT_HAS_ERRORS = "CONFLICT_IMPORT_HAS_ERRORS"
    CONFLICT_UPDATE_FAILED = "CONFLICT_UPDATE_FAILED"
    CONFLICT_APPLY_RECALC_FAILED = "CONFLICT_APPLY_RECALC_FAILED"

    # Semantic (422)
    SEMANTIC_VALIDATION_ERROR = "SEMANTIC_VALIDATION_ERROR"
    SEMANTIC_INVALID_TAX_MODE = "SEMANTIC_INVALID_TAX_MODE"
    SEMANTIC_MISSING_DECISION_ID = "SEMANTIC_MISSING_DECISION_ID"

    # Internal (500)
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INTERNAL_QUERY_FAILED = "INTERNAL_QUERY_FAILED"
    INTERNAL_IMPORT_FAILED = "INTERNAL_IMPORT_FAILED"

